# Server Configuration
server.port=8080

# Spring Application Name
spring.application.name=demo

# MySQL DataSource Configuration
spring.datasource.url=jdbc:mysql://db-mysql-nyc1-74304-do-user-22551525-0.f.db.ondigitalocean.com:25060/data_storage
spring.datasource.username=doadmin
spring.datasource.password=AVNS_E0T37KXtImSnB9zDF0b
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Management Endpoints Configuration (For health, metrics, and Prometheus)
management.endpoints.web.exposure.include=health,metrics,prometheus

# Prometheus Metrics Exporter Configuration
spring.metrics.export.prometheus.enabled=true

gremlin.teamId=e0faf9c4-1255-401c-baf9-c41255d01c70
gremlin.apiKey=c6d93755b666200657f9ad97b6c696dc0ad0072531716186c11eb781cc9e2f16

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zimmendrah@gmail.com
spring.mail.password=dfmv lgsm lxaa ldrs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=zimmendrah@gmail.com
